<!ELEMENT publica EMPTY>

<!ELEMENT extra ANY>

<!ELEMENT email (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>

<!ELEMENT libro (#PCDATA)>
<!ELEMENT revista (#PCDATA)>

<!-- 
Biblioteca tiene tres tipos de elementos
 - libro: aparece 1 o más veces
 - revista: aparece 0 o más veces
 - contacto: aparece 1 vez
-->
<!ELEMENT biblioteca (publica?, libro+, revista*, contacto)>

<!--
Un contacto puede tener o un email o un telefono, 
pero no puede estar vacío o tener ambas. 
Puede tener contenido extra.
-->
<!ELEMENT contacto ((email | telefono), extra?)>
